### PR TITLE
Added support of namespaced package names to routes

### PR DESCRIPTION
**Pull request by vanodevium**

### CODE REVIEW

**Comment by arve0** [comment]
They should already be supported with URL-encoding, is that not the case?

**Comment by vanodevium** [comment]
In my case tests show errors without this changes.

**Comment by vanodevium** [comment]
And [https://arve0.github.io/npm-download-size/#@jest/core](https://arve0.github.io/npm-download-size/#@jest/core) shows 500 error

**Comment by vanodevium** [comment]
So if you open [https://npm-download-size.seljebu.no/@jest/core](https://npm-download-size.seljebu.no/@jest/core) you will see exactly express error

**Comment by arve0** [comment]
You need to url-encode the package name: https://npm-download-size.seljebu.no/@jest%2fcore

Note that the service has been down a while, as the server had run out of disk space. It should be up now.

**Pull request closed without merging**
